# Maven

    
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
   google-chrome --version
   sudo apt install google-chrome-stable
   sudo apt-get install testng
   sudo apt-get install default-jdk
   sudo apt-get -y install xvfb
   cd /home/vsts/work/1/s/src/
   chmod +x chromedriver   
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: PublishPipelineArtifact@1
  inputs:
      targetPath: '$(Build.SourcesDirectory)/logs'
      artifact: 'Logs'
      publishLocation: 'pipeline'
  condition: always()

- task: PublishPipelineArtifact@1
  inputs:
      targetPath: '$(Build.SourcesDirectory)/target'
      artifact: 'Target results'
      publishLocation: 'pipeline'
  condition: succeededOrFailed()

schedules:
- cron: "43 23 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true

